PNDA-4431: Add basic platform test for Flink in PNDA
pndaproject/platform-testing pull request #60
Opened 2018-03-09 19:33 UTC by GaneshManal

# Problem Statement:
PNDA-4431: Add basic platform test for Flink in PNDA

# Change:
Added the flink plugin to platform testing which sends api request to the flink history server.
APIS being called -
- config - on success, reads flink version installed and add it to health matrix.
- joboverview - on success, adds the number of completed jobs to health matrix.

# Test details:
Verified the fix for AWS:
- UBUNTU - PICO -CDH & HDP
- UBUNTU - STD -CDH & HDP
- RHEL - PICO -CDH & HDP
- RHEL - STD -CDH & HDP
- Verification Done for openstack.

2018-03-14 16:04 UTC, jgarnier requested changes

2018-03-14 16:04 UTC, jgarnier commented on src/main/resources/plugins/flink/TestbotPlugin.py
> +                                         usage='%(prog)s [options]', description='Key metrics from CDH cluster')
replace 'Key metrics from CDH cluster' by 'Show state of Flink History server'

2018-03-14 16:27 UTC, jgarnier commented
could you also review the PYLINT output in order to improve code quality please?

2018-03-14 17:12 UTC, GaneshManal commented
Testbotplugin.py - pylint score = 9.26/10

2018-03-15 09:12 UTC, jgarnier requested changes

2018-03-15 09:12 UTC, jgarnier commented on src/main/resources/plugins/flink/TestbotPlugin.py
> +import requests
requests need to be imported before json and also group it with requests.exceptions

2018-03-15 09:12 UTC, jgarnier commented on src/main/resources/plugins/flink/TestbotPlugin.py
> +        history_server_available_success, history_server_completed_jobs_success = False, False
too long variable names, could you replace history_server_ by hs_ please

2018-03-16 08:55 UTC, merged